export const arr = [
  {
    id: 0,
    team1: 'GER',
    team2: 'ENG',
    flag1: 'img.jpg',
    flag2: 'img2.jpg',
    score1: '3',
    score2: '4',
  },
  {
    id: 1,
    team1: 'GER',
    team2: 'ENG',
    flag1: 'img.jpg',
    flag2: 'img2.jpg',
    score1: '3',
    score2: '4',
  },
  {
    id: 2,
    team1: 'GER',
    team2: 'ENG',
    flag1: 'img.jpg',
    flag2: 'img2.jpg',
    score1: '3',
    score2: '4',
  },
  {
    id: 3,
    team1: 'GER',
    team2: 'ENG',
    flag1: 'img.jpg',
    flag2: 'img2.jpg',
    score1: '3',
    score2: '4',
  },
  {
    id: 4,
    team1: 'GER',
    team2: 'ENG',
    flag1: 'img.jpg',
    flag2: 'img2.jpg',
    score1: '3',
    score2: '4',
  },
  {
    id: 5,
    team1: 'GER',
    team2: 'ENG',
    flag1: 'img.jpg',
    flag2: 'img2.jpg',
    score1: '3',
    score2: '4',
  },
];
