export const initState = {
  round16: [
    {
      homeTeam: 'Wales',
      homeFlag: 'https://www.uefa.com/imgml/flags/70x70/WAL.png?imwidth=276',
      awayTeam: 'Denmark',
      awayFlag: 'https://www.uefa.com/imgml/flags/70x70/DEN.png?imwidth=276',
      homeScore: 0,
      awayScore: 4,
      winner: 'away',
    },
    {
      homeTeam: 'Italy',
      homeFlag: 'https://www.uefa.com/imgml/flags/70x70/ITA.png?imwidth=276',
      awayTeam: 'Austria',
      awayFlag: 'https://www.uefa.com/imgml/flags/70x70/AUT.png?imwidth=276',
      homeScore: 2,
      awayScore: 1,
      winner: 'home',
    },
    {
      homeTeam: 'Netherlands',
      homeFlag: 'https://www.uefa.com/imgml/flags/70x70/NED.png?imwidth=276',
      awayTeam: 'Czech Republic',
      awayFlag: 'https://www.uefa.com/imgml/flags/70x70/CZE.png?imwidth=276',
      homeScore: 0,
      awayScore: 2,
      winner: 'away',
    },
    {
      homeTeam: 'Belgium',
      homeFlag: 'https://www.uefa.com/imgml/flags/70x70/BEL.png?imwidth=276',
      awayTeam: 'Portugal',
      awayFlag: 'https://www.uefa.com/imgml/flags/70x70/POR.png?imwidth=276',
      homeScore: 1,
      awayScore: 0,
      winner: 'home',
    },
    {
      homeTeam: 'Croatia',
      homeFlag: 'https://www.uefa.com/imgml/flags/70x70/CRO.png?imwidth=276',
      awayTeam: 'Spain',
      awayFlag: 'https://www.uefa.com/imgml/flags/70x70/ESP.png?imwidth=276',
      homeScore: 3,
      awayScore: 5,
      winner: 'away',
    },
    {
      homeTeam: 'France',
      homeFlag: 'https://www.uefa.com/imgml/flags/70x70/FRA.png?imwidth=276',
      awayTeam: 'Switzerland',
      awayFlag: 'https://www.uefa.com/imgml/flags/70x70/SUI.png?imwidth=276',
      homeScore: 3,
      awayScore: 3,
      winner: 'away',
    },
    {
      homeTeam: 'England',
      homeFlag: 'https://www.uefa.com/imgml/flags/70x70/ENG.png?imwidth=276',
      awayTeam: 'Germany',
      awayFlag: 'https://www.uefa.com/imgml/flags/70x70/GER.png?imwidth=276',
      homeScore: '',
      awayScore: '',
      winner: '-',
    },
    {
      homeTeam: 'Sweden',
      homeFlag: 'https://www.uefa.com/imgml/flags/70x70/SWE.png?imwidth=276',
      awayTeam: 'Ukraine',
      awayFlag: 'https://www.uefa.com/imgml/flags/70x70/UKR.png?imwidth=276',
      homeScore: '',
      awayScore: '',
      winner: '-',
    },
  ],
  quarterFinals: [
    {
      homeTeam: 'Switzerland',
      homeFlag: 'https://www.uefa.com/imgml/flags/70x70/SUI.png?imwidth=276',
      awayTeam: 'Spain',
      awayFlag: 'https://www.uefa.com/imgml/flags/70x70/ESP.png?imwidth=276',
      homeScore: '',
      awayScore: '',
      winner: '-',
    },
    {
      homeTeam: 'Belgium',
      homeFlag: 'https://www.uefa.com/imgml/flags/70x70/BEL.png?imwidth=276',
      awayTeam: 'Italy',
      awayFlag: 'https://www.uefa.com/imgml/flags/70x70/ITA.png?imwidth=276',
      homeScore: '',
      awayScore: '',
      winner: '-',
    },
    {
      homeTeam: 'Czech Republic',
      homeFlag: 'https://www.uefa.com/imgml/flags/70x70/CZE.png?imwidth=276',
      awayTeam: 'Denmark',
      awayFlag: 'https://www.uefa.com/imgml/flags/70x70/DEN.png?imwidth=276',
      homeScore: '',
      awayScore: '',
      winner: '-',
    },
    {
      homeTeam: '',
      homeFlag: 'https://img.uefa.com/imgml/TP/teams/logos/teamlogo_fallback.svg?imwidth=276',
      awayTeam: '',
      awayFlag: 'https://img.uefa.com/imgml/TP/teams/logos/teamlogo_fallback.svg?imwidth=276',
      homeScore: '',
      awayScore: '',
      winner: '-',
    },
  ],
  semiFinals: [
    {
      homeTeam: '',
      homeFlag: 'https://img.uefa.com/imgml/TP/teams/logos/teamlogo_fallback.svg?imwidth=276',
      awayTeam: '',
      awayFlag: 'https://img.uefa.com/imgml/TP/teams/logos/teamlogo_fallback.svg?imwidth=276',
      homeScore: '',
      awayScore: '',
      winner: '-',
    },
    {
      homeTeam: '',
      homeFlag: 'https://img.uefa.com/imgml/TP/teams/logos/teamlogo_fallback.svg?imwidth=276',
      awayTeam: '',
      awayFlag: 'https://img.uefa.com/imgml/TP/teams/logos/teamlogo_fallback.svg?imwidth=276',
      homeScore: '',
      awayScore: '',
      winner: '-',
    },
  ],
  final: [
    {
      homeTeam: '',
      homeFlag: 'https://img.uefa.com/imgml/TP/teams/logos/teamlogo_fallback.svg?imwidth=276',
      awayTeam: '',
      awayFlag: 'https://img.uefa.com/imgml/TP/teams/logos/teamlogo_fallback.svg?imwidth=276',
      homeScore: '',
      awayScore: '',
      winner: '-',
    },
  ],
};
